#podman run --rm \
#--privileged \
#-p 9090:9090 \
#-v ./config/reader:/etc/prometheus \
#prom/prometheus \
#--config.file=/etc/prometheus/prometheus.yml \
#--web.enable-remote-write-receiver

services:
  read:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - poulet_internal
    volumes:
      - ./cloud/config/read:/etc/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - poulet_internal
    volumes:
      - ./cloud/config/alertmanager:/etc/alertmanager
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
  #  env_file:
  #    - ./cloud/config/alertmanager/.env
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - poulet_internal
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true #Enabled the Anonymous user no user/pass needed
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin #Activate the ROLE VIEWER as Default
      - GF_AUTH_BASIC_ENABLED=false #Disable the AUTH Method
      - GF_AUTH_DISABLE_LOGIN_FORM=true #Disable the login on show
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true #Diabled the menu
      - GF_SECURITY_ALLOW_EMBEDDING=true #Allow IFRAME Calls
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVE_FROM_SUB_PATH=true
    #env_file:
    #  - ./cloud/config/grafana/.env
    volumes:
      - ./cloud/config/grafana/provisioning/data_sources:/etc/grafana/provisioning/datasources/
      - ./cloud/config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - ./cloud/config/grafana/dashboards_data:/var/lib/grafana/dashboards/
      - ./cloud/config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /etc/localtime:/etc/localtime:ro
  mongodb:
    image: mongodb/mongodb-community-server:7.0.2-ubi8
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 27017:27017
    networks:
      - poulet_internal
  keycloak:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:8080
    networks:
      - poulet_internal
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev

networks:
  poulet_internal:
    name: poulet_internal