#podman run --rm \
#--privileged \
#-p 9090:9090 \
#-v ./config/reader:/etc/prometheus \
#prom/prometheus \
#--config.file=/etc/prometheus/prometheus.yml \
#--web.enable-remote-write-receiver

services:
  read:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./server/config/read:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true #Enabled the Anonymous user no user/pass needed
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin #Activate the ROLE VIEWER as Default
      - GF_AUTH_BASIC_ENABLED=false #Disable the AUTH Method
      - GF_AUTH_DISABLE_LOGIN_FORM=true #Disable the login on show
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true #Diabled the menu
      - GF_SECURITY_ALLOW_EMBEDDING=true #Allow IFRAME Calls
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVE_FROM_SUB_PATH=true
    env_file:
      - ./server/config/grafana/.env
    volumes:
      - ./server/config/grafana/provisioning/data_sources:/etc/grafana/provisioning/datasources/
      - ./server/config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - ./server/config/grafana/dashboards_data:/var/lib/grafana/dashboards/
      - ./server/config/grafana/grafana.ini:/etc/grafana/grafana.ini
  write:
    build:
      context: ./gateway/batch-send
    environment:
      - PROMETHEUS_SERVER=http://read:9090/api/v1/write
    depends_on:
      - read
  mongodb:
    image: mongodb/mongodb-community-server:7.0.2-ubi8
    ports:
      - 27017:27017
  keycloak:
    ports:
      - 8081:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev
