services:

  adapter:
    build:
      context: ./adapter
    environment:
      - RABBITMQ_SERVER=rabbitmq:5672
      - SERVER_PORT=8080
    depends_on:
      - rabbitmq
    networks: 
      - internal

  data-manager:
    build:
      context: ./dataManager
    environment:
      - PROMETHEUS_SERVER=http://read:9090/api/v1/write
      - RABBITMQ_SERVER=rabbitmq:5672
    depends_on:
      - rabbitmq
    networks: 
      - internal
  
  rabbitmq:
    image: rabbitmq:management
    ports: 
      - 127.0.0.1:5672:5672
      - 127.0.0.1:8080:15672
    networks: 
      - internal
  
networks:
  internal:
