services:

  adapter:
    build:
      context: ./adapter
    environment:
      - RABBITMQ_SERVER=rabbitmq:5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 0.0.0.0:8088:8080
    depends_on:
      - rabbitmq
    networks: 
      - internal

  data-manager:
    build:
      context: ./dataManager
    environment:
      - PROMETHEUS_SERVER=http://read:9090/api/v1/write
      - RABBITMQ_SERVER=rabbitmq:5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - NOTIFICATION_SERVER=http://alert-management:8082
      - CLIENT_INFO_SERVER=http://patient-management:8083
      - GATEWAY_ID=671954d2490bd363cd077544
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - rabbitmq
    networks: 
      - internal
      - poulet_internal
  
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 127.0.0.1:5672:5672
      - 127.0.0.1:8080:15672
    networks: 
      - internal
  
networks:
  internal:
  poulet_internal:
    external: true
