FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-23 

## install maven with curl
# https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
USER    root
RUN curl -fsSL -o /tmp/apache-maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
RUN tar -xzf /tmp/apache-maven.tar.gz -C /opt/
RUN ln -s /opt/apache-maven-3.9.9 /opt/maven
ENV PATH="/opt/maven/bin:${PATH}"
USER quarkus