/* tslint:disable */
/* eslint-disable */
/**
 * alert-management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Severity } from './severity';

/**
 * 
 * @export
 * @interface AlertDTO
 */
export interface AlertDTO {
    /**
     * 
     * @type {string}
     * @memberof AlertDTO
     */
    'time': string;
    /**
     * 
     * @type {string}
     * @memberof AlertDTO
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof AlertDTO
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof AlertDTO
     */
    'gatewayId': string;
    /**
     * 
     * @type {number}
     * @memberof AlertDTO
     */
    'value'?: number;
    /**
     * 
     * @type {Severity}
     * @memberof AlertDTO
     */
    'severity': Severity;
}



