/* tslint:disable */
/* eslint-disable */
/**
 * alert-management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Severity } from './severity';

/**
 * 
 * @export
 * @interface Alert
 */
export interface Alert {
    /**
     * Alert ID as a 24-character hexadecimal string
     * @type {string}
     * @memberof Alert
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'time'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'gatewayId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'timestamp'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Alert
     */
    'treated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Alert
     */
    'modified'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    'value'?: number;
    /**
     * 
     * @type {Severity}
     * @memberof Alert
     */
    'severity'?: Severity;
}



