apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: default  # Change this if you're using a different namespace
data:
  env.json: |  # Use a multi-line string
    {
      "ALERT_MANAGEMENT_BASE_URL": "{{ .Values.environment.ALERT_MANAGEMENT_BASE_URL }}",
      "PATIENT_MANAGEMENT_BASE_URL": "{{ .Values.environment.PATIENT_MANAGEMENT_BASE_URL }}",
      "ANALYSE_HAUT_NIVEAU_MANAGEMENT_BASE_URL": "{{ .Values.environment.ANALYSE_HAUT_NIVEAU_MANAGEMENT_BASE_URL }}"
    }