{
 "title": "Doctor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gatewayId", "label": "gatewayId" }
  ]
 },
 "panels": [
  {
   "title": "Client informations",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## Firsst name : Marie \n## Last name : Dupont\n## Age : 78\n## Sexe : F"
   }
  },
  {
   "title": "Heart rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "heartrate{gateway_id=\"$gatewayId\"}",
     "legendFormat": "frequency in bpm"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "temperature{gateway_id=\"$gatewayId\"}",
     "legendFormat": "degrees"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "acceleration{gateway_id=\"$gatewayId\"}",
     "legendFormat": "acceleration"
    }
   ]
  }
 ]
}