apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://traefik.github.io/charts