{{- if  not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-alert-secret
type: Opaque
data:
  clientId: {{ .Values.keycloak.clientId | b64enc }}
  clientSecret: {{ .Values.keycloak.clientSecret | b64enc }}
{{- end }}