# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

#Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/deriv_rules/glucoseD.yml"
  - "rules/deriv_rules/temperatureD.yml"
  - "rules/deriv_rules/heartrateD.yml"
  
  - "rules/predict_rules/glucoseP.yml"
  - "rules/predict_rules/temperatureP.yml"
  - "rules/predict_rules/heartrateP.yml"
  
  
  - "rules/temperature_alerts.yml"
  - "rules/acceleration_alerts.yml"
  - "rules/glucose_alerts.yml"
  - "rules/heartrate_alerts.yml"

# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
