groups:
- name: acceleration-alerts
  rules:
  - alert: HighAcceleration
    expr: acceleration > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Acceleration Alert"
      description: "Acceleration exceeds 80 units."
