groups:
- name: glucose-alerts
  rules:
  - alert: HighGlucose
    expr: glucose > 180
    for: 30s
    labels:
      severity: "WARNING" 
      type: "glucose"      
      gatewayId: "67325277b01fb040f8e73672" 
      value: "{{ $value  }}" 

    annotations:
      summary: "High Glucose Alert"
      description: "Glucose level is above 180 mg/dL."
      message: "Current glucose value: {{ $value }}"  

  - alert: LowGlucose
    expr: glucose < 70
    for: 30s
    labels:
      severity: "WARNING" 
      type: "glucose"     
      gatewayId: "67325277b01fb040f8e73672"  
      value: "{{ $value }}"
    annotations:
      summary: "Low Glucose Alert"
      description: "Glucose level is below 70 mg/dL."
      message: "Current glucose value: {{ $value }}"  
