groups:
- name: glucose-alerts
  rules:
  - alert: HighGlucose
    expr: glucose > 180
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Glucose Alert"
      description: "Glucose level is above 180 mg/dL."
      
  - alert: LowGlucose
    expr: glucose < 70
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low Glucose Alert"
      description: "Glucose level is below 70 mg/dL."
