groups:
- name: glucose-alerts
  rules:
  - alert: HighGlucose
    expr: glucose > 180
    for: 30s
    labels:
      severity: "WARNING" 
      type: "GLUCOSE"      
      gatewayId: "example-gateway-id" 
      value: "{{ $value | int }}" 

    annotations:
      summary: "High Glucose Alert"
      description: "Glucose level is above 180 mg/dL."
      message: "Current glucose value: {{ $value }}"  
      time: "{{ .StartsAt }}" 

  - alert: LowGlucose
    expr: glucose < 70
    for: 30s
    labels:
      severity: "WARNING" 
      type: "GLUCOSE"     
      gatewayId: "example-gateway-id"  
      value: "{{ $value | int }}"
    annotations:
      summary: "Low Glucose Alert"
      description: "Glucose level is below 70 mg/dL."
      message: "Current glucose value: {{ $value }}"  
      time: "{{ .StartsAt }}" 
