groups:
- name: heartrate-alerts
  rules:
  - alert: HighHeartRate
    expr: heartrate > 100
    for: 30s
    labels:
      severity: "WARNING"  
      type: "HEART_RATE"  
      gatewayId: "example-gateway-id"  
      value: "{{ $value | int }}"

    annotations:
      summary: "High Heart Rate Alert"
      description: "Heart rate is above 100 bpm."
      message: "Current heart rate value: {{ $value }}"  
      time: "{{ .StartsAt }}" 

  - alert: LowHeartRate
    expr: heartrate < 50
    for: 30s
    labels:
      severity: "WARNING"  
      type: "HEART_RATE"  
      gatewayId: "example-gateway-id"
      value: "{{ $value | int }}"

    annotations:
      summary: "Low Heart Rate Alert"
      description: "Heart rate is below 50 bpm."
      message: "Current heart rate value: {{ $value }}"  
      time: "{{ .StartsAt }}"  
