groups:
- name: temperature-deriv-alerts
  rules:
  - alert: RapidIncreaseTemperature
    expr: deriv(temperature[30s]) > 0.5
    for: 15s
    labels:
      severity: "MEDIUM"
      type: "temperature_deriv"
      gatewayId: "671aaecbbf1f103b28e58788"
      value: "{{ $value }}"

    annotations:
      summary: "Rapid Increase in Temperature Alert"
      description: "The temperature is increasing rapidly (rate of change > 0.5째C per 5 minutes)."
      message: "Current rate of temperature change: {{ $value }}째C per 5 minutes"

  - alert: RapidDecreaseTemperature
    expr: deriv(temperature[30s]) < -0.5
    for: 15s
    labels:
      severity: "MEDIUM"
      type: "temperature_deriv"
      gatewayId: "671aaecbbf1f103b28e58788"
      value: "{{ $value }}"

    annotations:
      summary: "Rapid Decrease in Temperature Alert"
      description: "The temperature is decreasing rapidly (rate of change < -0.5째C per 5 minutes)."
      message: "Current rate of temperature change: {{ $value }}째C per 5 minutes"
