apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  interval: 60m
  chart:
    spec:
      chart: mongodb
      version: "16.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values: {}
