apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 60m
  chart:
    spec:
      chart: keycloak
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values: {}
