/* tslint:disable */
/* eslint-disable */
/**
 * patient-management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatientDTO
 */
export interface PatientDTO {
    /**
     * 
     * @type {string}
     * @memberof PatientDTO
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof PatientDTO
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof PatientDTO
     */
    'gender': string;
    /**
     * 
     * @type {string}
     * @memberof PatientDTO
     */
    'emergencyContactPhoneNumber': string;
}

