apiVersion: v2
name: poulet
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.3"

dependencies:
  - name: grafana
    version: "8.5.1"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: keycloak
    version: "24.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  - name: mongodb
    version: 16.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: alert-management
    version: 0.1.0
    condition: alert-management.enabled
  - name: patient-management
    version: 0.1.0
    condition: patient-management.enabled
  - name: frontend
    version: 0.2.2
    #condition: frontend.enabled
  - name: analyse-haut-niveau-management
    version: 0.2.0
    condition: analyse-haut-niveau-management.enabled