apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter
  labels:
    app: adapter
spec:
  selector:
    matchLabels:
      app: adapter
  template:
    metadata:
      labels:
        app: adapter
    spec:
      containers:
        - name: adapter
          image: "ghcr.io/startupnationlabs/poulet/adpater:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: RABBITMQ_SERVER
              value: "rabbitmq:5672"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: adapter
  labels:
    app: adapter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: adapter
