apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager
  labels:
    app: data-manager
spec:
  selector:
    matchLabels:
      app: data-manager
  template:
    metadata:
      labels:
        app: data-manager
    spec:
      containers:
        - name: data-manager
          image: "ghcr.io/startupnationlabs/poulet/gateway-datamanager:2bf9fb5096163fd8b7332cb0e9d07253e03ff39f"
          env:
            - name: RABBITMQ_SERVER
              value: "rabbitmq:5672"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: data-manager
  labels:
    app: data-manager
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: data-manager