apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  interval: 60m
  chart:
    spec:
      chart: rabbitmq
      version: "15.0.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values: {}