groups:
  - name: health_alerts
    rules:
      - alert: FallDetected
        expr: fall_detected{patient_id="1"} > 0 
        for: 5m 
        labels:
          severity: critical
        annotations:
          summary: "Chute détectée"
          description: "Une chute a été détectée sur le patient {{ $labels.patient_id }}."
