---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . | trunc 63 | trimSuffix "-" }}-keycloak-db-username
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.keycloak.db.username | b64enc }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  db:
    host: {{ .Values.keycloak.db.host }}
    usernameSecret:
      name: {{ include "keycloak.fullname" . | trunc 63 | trimSuffix "-" }}-keycloak-db-username
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.db.passwordSecretName}}
      key: {{ .Values.keycloak.db.passwordSecretKey }}
    vendor: postgres
    database: postgres
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
  instances: 1
  ingress:
    enabled: false
  additionalOptions:
    - name: proxy-address-forwarding
      value: "true"
    - name: proxy
      value: edge

