apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 60m
  chart:
    spec:
      chart: prometheus
      version: "25.26.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  values: {}
