- name: heartrate-alerts
  rules:
  - alert: AvgIncreaseHeartrate
    expr: avg_over_time(heartrate[10s]) > 15
    for: 5s
    labels:
      severity: "WARNING"
      type: "heartrate_avg_increase"
      gatewayId: "{{ $labels.gateway_id }}"
      value: "{{ $value  }}" 
    annotations:
      summary: "Rapid Increase in Heart Rate Alert"
      description: "The heart rate is decreasing rapidly (rate of change > 15 bpm per 5 minutes)"
      message: "Current rate of heart rate change: {{ $value }} bpm per 5 minutes"

    - alert: AvgDecreaseHeartrate
    expr: avg_over_time(heartrate[10s]) < -15
    for: 15s
    labels:
      severity: "WARNING"
      type: "heartrate_avg_decrease"
      gatewayId: "{{ $labels.gateway_id }}"
      value: "{{ $value }}"

    annotations:
      summary: "Rapid Decrease in Heart Rate Alert"
      description: "The heart rate is decreasing rapidly (rate of change < -15 bpm per 5 minutes)."
      message: "Current rate of heart rate change: {{ $value }} bpm per 5 minutes"
