name: Docker Build and Push Gateway Images
on:
  push:
    branches:
      - main
      - fix-ci
      - helm-chart

permissions: write-all

jobs:
  build-push-gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: [adapter, dataManager, AlerteDetector]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO name as output
        id: downcase
        run: |
          echo "::set-output name=downcase::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

      - name: downcase APPLICATION name as output
        id: downcase-application
        run: |
          echo "::set-output name=downcase::$(echo ${{ matrix.application }} | tr '[:upper:]' '[:lower:]')"
      - name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: gateway/${{ matrix.application }}
          tags: ghcr.io/${{ steps.downcase.outputs.downcase }}/gateway-${{ steps.downcase-application.outputs.downcase }}:${{ github.sha }}, ghcr.io/${{ steps.downcase.outputs.downcase }}/gateway-${{  steps.downcase-application.outputs.downcase }}:${{ github.ref_name }}

